export const LOADING_EVENTSAT = "LOADING_USER";

export const CREATE_EVENTSAT = "CREATE_EVENTSAT";
export const GET_EVENTSATS = "GET_EVENTSATS";
export const GET_EVENTSAT = "GET_EVENTSAT";
export const UPDATE_EVENTSAT = "UPDATE_EVENTSAT";
export const DELETE_EVENTSAT = "DELETE_EVENTSAT";
export const DELETE_EVENTSATS = "DELETE_EVENTSATS";
