export const LOADING_LOCATION = "LOADING_USER";

export const CREATE_LOCATION = "CREATE_LOCATION";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_LOCATION = "GET_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const DELETE_LOCATIONS = "DELETE_LOCATIONS";
