export const LOADING_UNIVERSITIESCREATED = "LOADING_USER";

export const CREATE_UNIVERSITIESCREATED = "CREATE_UNIVERSITIESCREATED";
export const GET_UNIVERSITIESCREATEDS = "GET_UNIVERSITIESCREATEDS";
export const GET_UNIVERSITIESCREATED = "GET_UNIVERSITIESCREATED";
export const UPDATE_UNIVERSITIESCREATED = "UPDATE_UNIVERSITIESCREATED";
export const DELETE_UNIVERSITIESCREATED = "DELETE_UNIVERSITIESCREATED";
export const DELETE_UNIVERSITIESCREATEDS = "DELETE_UNIVERSITIESCREATEDS";
