export const LOADING_RSOEVENT = "LOADING_USER";

export const CREATE_RSOEVENT = "CREATE_RSOEVENT";
export const GET_RSOEVENTS = "GET_RSOEVENTS";
export const GET_RSOEVENT = "GET_RSOEVENT";
export const UPDATE_RSOEVENT = "UPDATE_RSOEVENT";
export const DELETE_RSOEVENT = "DELETE_RSOEVENT";
export const DELETE_RSOEVENTS = "DELETE_RSOEVENTS";
