export const LOADING_PRIVATEEVENT = "LOADING_USER";

export const CREATE_PRIVATEEVENT = "CREATE_PRIVATEEVENT";
export const GET_PRIVATEEVENTS = "GET_PRIVATEEVENTS";
export const GET_PRIVATEEVENT = "GET_PRIVATEEVENT";
export const UPDATE_PRIVATEEVENT = "UPDATE_PRIVATEEVENT";
export const DELETE_PRIVATEEVENT = "DELETE_PRIVATEEVENT";
export const DELETE_PRIVATEEVENTS = "DELETE_PRIVATEEVENTS";
