export const LOADING_PUBLICEVENT = "LOADING_USER";

export const CREATE_PUBLICEVENT = "CREATE_PUBLICEVENT";
export const GET_PUBLICEVENTS = "GET_PUBLICEVENTS";
export const GET_PUBLICEVENT = "GET_PUBLICEVENT";
export const UPDATE_PUBLICEVENT = "UPDATE_PUBLICEVENT";
export const DELETE_PUBLICEVENT = "DELETE_PUBLICEVENT";
export const DELETE_PUBLICEVENTS = "DELETE_PUBLICEVENTS";
